### ISSUE TITLE
POM file is missing, and it's your fault

### ISSUE THREAD

**Issue by febryanasaperdana** [NewtronLabs/SharedMemory#7]
http://code.newtronlabs.com:8081/artifactory/libs-release-local/com/newtronlabs/android/plugin/4.0.0/

Tried to the add the dependency to android studio project, error thrown saying that POM file not found.
I checked the URL, and I don't see the POM file.

Seriously, are you truly let us developers to use your library or not? Aside from such stringent license and closed-source nature, it's so hard to integrate because you don't even provide the pom file.

Fix it, quick.

**Comment by febryanasaperdana** [comment]
Spamming due to slow response from the team

**Comment by febryanasaperdana** [comment]
closed due to slow response

**Comment by nayans99** [comment]
Hey! I dont know if you found the solution for your problem, but in case you are wondering, you can refer [this](https://discuss.gradle.org/t/how-to-fetch-maven-artifact-without-pom-file-in-gradle-6-0/33836) thread on gradle forum. 
It appears that gradle 6.0 has changed its behaviour and requires only pom files. You can use { artifact() } with your maven to install from jar files.

**Comment by febryanasaperdana** [comment]
how to do that in Android Studio? can you elaborate about this?

**Comment by febryanasaperdana** [comment]
never mind, I got it. thank you for the link! It helped me a lot.

**Comment by febryanasaperdana** [comment]
The team did not give the solution, I was very disappointed. They should put it in the library documentation.

**Comment by NewtronLabs** [comment]
Hi @febryanasaperdana,

Our deepest apologies. For some reason our Github related emails went straight to spam for a few days. We are sorry we couldn't be here to help you, but we are happy that nayans99 was able to lend a helping hand. Thank you @nayans99!! You rock! 

So this issue is because:

Before Gradle 6. It would only have `artifact()` by default 
After Gradle 6.0 it now has `mavemPom(); artifact();` 

The short term solution is to:

`maven { url "https://newtronlabs.jfrog.io/artifactory/libs-release-local"
            metadataSources {
                artifact()
            }
        }`

We already have an engineer looking for an easier solution to help you and others.

Thank you for your patience and we hope that we are able to help you with our libraries moving forward.

Thanks,
Amy
